version: "3" # Version of docker compose .yml file
services: # Specify services. Each service will run in container
    redis-server: # Redis image will be built from Dockerfile and run in the container
        build:
            context: .
            dockerfile: Dockerfile-redis
    node-app: # Node app image will be built from Dockerfile and run in the container
        build:
            context: .
            dockerfile: Dockerfile-node
        ports:
            - "8000:8000" # Map Local machine port to container port
